services:
  chinesesubfinder:
    image: ${CSF_IMAGE:-ghcr.io/morningstar-ski/chinesesubfinder-optimization:latest}
    container_name: chinesesubfinder
    hostname: chinesesubfinder
    restart: always
    environment:
      PUID: ${PUID:-1026}
      PGID: ${PGID:-100}
      PERMS: ${PERMS:-true}
      TZ: ${TZ:-Asia/Shanghai}
      UMASK: ${UMASK:-022}
    ports:
      - "19035:19035"
      - "19037:19037"
    volumes:
      - ./config:/config
      - ./media:/media
      - ./browser:/root/.cache/rod/browser
